Commented out build steps

diff --git a/docker/Dockerfile.sealights b/docker/Dockerfile.sealights
--- a/docker/Dockerfile.sealights
+++ b/docker/Dockerfile.sealights
@@ -71,14 +71,14 @@ RUN NODE_HEADERS_VERSION=$(node --version); echo "=== Install node headers $NODE
 # Increase timeout for yarn install
 RUN "$YARN" config set httpTimeout 600000
 
-RUN echo "=== YARN INSTALL ==="; FAILED=0; "$YARN" install --immutable; \
-  for d in /tmp/xfs-*; do if [[ -f ${d}/build.log ]]; then \
-  (( FAILED = FAILED + 1 )); \
-  echo; echo $d; \
-  echo "!!! YARN INSTALL FAILED !!!"; \
-  cat ${d}/build.log; \
-  fi; done; \
-  if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
+#RUN echo "=== YARN INSTALL ==="; FAILED=0; "$YARN" install --immutable; \
+#  for d in /tmp/xfs-*; do if [[ -f ${d}/build.log ]]; then \
+#  (( FAILED = FAILED + 1 )); \
+#  echo; echo $d; \
+#  echo "!!! YARN INSTALL FAILED !!!"; \
+#  cat ${d}/build.log; \
+#  fi; done; \
+#  if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
 
 # Stage 3 - Build packages
 FROM deps AS build
@@ -100,33 +100,33 @@ RUN \
   cat packages/app/src/build-metadata.json; echo
 
 # suppress git warnings about dubious ownership in repository at '/opt/app-root/src' when building
-RUN echo "=== YARN BUILD ==="; FAILED=0; \
-  git config --global --add safe.directory /opt/app-root/src; \
-  "$YARN" build || true; \
-  for d in $(find . -name yarn-install.log); do \
-  (( FAILED = FAILED + 1 )); echo; echo $d; echo "======"; cat ${d}; \
-  done; \
-  if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
+#RUN echo "=== YARN BUILD ==="; FAILED=0; \
+#  git config --global --add safe.directory /opt/app-root/src; \
+#  "$YARN" build || true; \
+#  for d in $(find . -name yarn-install.log); do \
+#  (( FAILED = FAILED + 1 )); echo; echo $d; echo "======"; cat ${d}; \
+#  done; \
+#  if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
 
 WORKDIR $CONTAINER_SOURCE/dynamic-plugins
 
-RUN echo "=== DYNAMIC PLUGIN YARN INSTALL ==="; FAILED=0; "$YARN" install --immutable; \
-  for d in /tmp/xfs-*; do if [[ -f ${d}/build.log ]]; then \
-  (( FAILED = FAILED + 1 )); \
-  echo; echo $d; \
-  echo "!!! DYNAMIC PLUGIN YARN INSTALL FAILED !!!"; \
-  cat ${d}/build.log; \
-  fi; done; \
-  if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
+#RUN echo "=== DYNAMIC PLUGIN YARN INSTALL ==="; FAILED=0; "$YARN" install --immutable; \
+#  for d in /tmp/xfs-*; do if [[ -f ${d}/build.log ]]; then \
+#  (( FAILED = FAILED + 1 )); \
+#  echo; echo $d; \
+#  echo "!!! DYNAMIC PLUGIN YARN INSTALL FAILED !!!"; \
+#  cat ${d}/build.log; \
+#  fi; done; \
+#  if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
 
-RUN echo "=== EXPORT DYNAMIC PLUGINS ==="; FAILED=0; \
-  "$YARN" export-dynamic || true; \
-  for d in $(find . -name yarn-install.log); do \
-  (( FAILED = FAILED + 1 )); echo; echo $d; echo "======"; cat ${d}; \
-  done; \
-  if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
+#RUN echo "=== EXPORT DYNAMIC PLUGINS ==="; FAILED=0; \
+#  "$YARN" export-dynamic || true; \
+#  for d in $(find . -name yarn-install.log); do \
+#  (( FAILED = FAILED + 1 )); echo; echo $d; echo "======"; cat ${d}; \
+#  done; \
+#  if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
 
-RUN echo "=== YARN COPY DYNAMIC PLUGINS in $(pwd) ==="; "$YARN" copy-dynamic-plugins dist
+#RUN echo "=== YARN COPY DYNAMIC PLUGINS in $(pwd) ==="; "$YARN" copy-dynamic-plugins dist
 
 WORKDIR $CONTAINER_SOURCE
 
@@ -165,11 +165,11 @@ RUN "$YARN" config set httpTimeout 600000
 
 # Install production dependencies
 # hadolint ignore=DL3059
-RUN echo "=== YARN WORKSPACES FOCUS ==="; FAILED=0; "$YARN" workspaces focus --all --production || true; \
-  for d in /tmp/xfs-*; do if [[ -f ${d}/build.log ]]; then \
-  (( FAILED = FAILED + 1 )); echo; echo $d; echo "======"; cat ${d}/build.log; \
-  fi; done; \
-  if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
+#RUN echo "=== YARN WORKSPACES FOCUS ==="; FAILED=0; "$YARN" workspaces focus --all --production || true; \
+#  for d in /tmp/xfs-*; do if [[ -f ${d}/build.log ]]; then \
+#  (( FAILED = FAILED + 1 )); echo; echo $d; echo "======"; cat ${d}/build.log; \
+#  fi; done; \
+#  if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
 
 RUN \
   # delete all the nested .npmrc files and set default values
