Commented out build steps - fix 1

diff --git a/docker/Dockerfile.sealights b/docker/Dockerfile.sealights
--- a/docker/Dockerfile.sealights
+++ b/docker/Dockerfile.sealights
@@ -135,13 +135,13 @@ WORKDIR $CONTAINER_SOURCE
 FROM skeleton AS cleanup
 
 # Upstream only - copy the install dependencies from the build stage and context
-COPY --from=build $CONTAINER_SOURCE/yarn.lock \
-  $CONTAINER_SOURCE/package.json \
-  ./
-COPY --from=build \
-  $CONTAINER_SOURCE/packages/backend/dist/skeleton.tar.gz \
-  $CONTAINER_SOURCE/packages/backend/dist/bundle.tar.gz \
-  ./packages/backend/dist/
+#COPY --from=build $CONTAINER_SOURCE/yarn.lock \
+#  $CONTAINER_SOURCE/package.json \
+#  ./
+#COPY --from=build \
+#  $CONTAINER_SOURCE/packages/backend/dist/skeleton.tar.gz \
+#  $CONTAINER_SOURCE/packages/backend/dist/bundle.tar.gz \
+#  ./packages/backend/dist/
 
 # unpack and remove tarballs
 ENV TARBALL_PATH=./packages/backend/dist
@@ -190,23 +190,23 @@ WORKDIR $CONTAINER_SOURCE/
 # Install techdocs dependencies using requirements files
 # hadolint ignore=DL3013,DL3041,SC2086
 COPY "$EXTERNAL_SOURCE_NESTED"/python/ ./python
-RUN microdnf install -y python3.11 python3.11-pip python3.11-devel make cmake cpp gcc gcc-c++ skopeo 1>/dev/null 2>&1; \
-  alternatives --install /usr/bin/python python /usr/bin/python3.11 1 && \
-  alternatives --install /usr/bin/pip pip /usr/bin/pip3.11 1 && \
-  # fix ownership for pip install folder
-  mkdir -p /opt/app-root/src/.cache/pip && chown -R root:root /opt/app-root && \
-  # ls -ld /opt/ /opt/app-root /opt/app-root/src/ /opt/app-root/src/.cache /opt/app-root/src/.cache/pip || true; \
-  pushd "$EXTERNAL_SOURCE_NESTED"/python/ >/dev/null && \
-  set -e; \
-  python3.11 -V; pip3.11 -V; \
-  pip install --no-cache-dir --upgrade pip setuptools pyyaml; \
-  pip install --no-cache-dir -r requirements.txt -r requirements-build.txt; mkdocs --version; \
-  popd >/dev/null; \
-  rm -fr python/; \
-  microdnf clean all
+#RUN microdnf install -y python3.11 python3.11-pip python3.11-devel make cmake cpp gcc gcc-c++ skopeo 1>/dev/null 2>&1; \
+#  alternatives --install /usr/bin/python python /usr/bin/python3.11 1 && \
+#  alternatives --install /usr/bin/pip pip /usr/bin/pip3.11 1 && \
+#  # fix ownership for pip install folder
+#  mkdir -p /opt/app-root/src/.cache/pip && chown -R root:root /opt/app-root && \
+#  # ls -ld /opt/ /opt/app-root /opt/app-root/src/ /opt/app-root/src/.cache /opt/app-root/src/.cache/pip || true; \
+#  pushd "$EXTERNAL_SOURCE_NESTED"/python/ >/dev/null && \
+#  set -e; \
+#  python3.11 -V; pip3.11 -V; \
+#  pip install --no-cache-dir --upgrade pip setuptools pyyaml; \
+#  pip install --no-cache-dir -r requirements.txt -r requirements-build.txt; mkdocs --version; \
+#  popd >/dev/null; \
+#  rm -fr python/; \
+#  microdnf clean all
 
 # Upstream only - copy from cleanup stage
-COPY --from=cleanup --chown=1001:1001 $CONTAINER_SOURCE/ ./
+#COPY --from=cleanup --chown=1001:1001 $CONTAINER_SOURCE/ ./
 # Downstream only - copy from build, not cleanup stage
 # COPY --from=build --chown=1001:1001 "$CONTAINER_SOURCE"/ ./
 
@@ -227,15 +227,15 @@ RUN chmod -R a+r ./install-dynamic-plugins.py; \
 # The existence of the index.html.tmpl tells Backstage to take that file and load it into memory, inject the needed appConfig (instead of writing
 # it into a random *.chunk.js file, and then serve that file from memory so that we can set the readOnlyRootFilesystem: true option for
 # the container.
-RUN ln -s /opt/app-root/src/packages/app/dist/index.html /opt/app-root/src/packages/app/dist/index.html.tmpl
+#RUN ln -s /opt/app-root/src/packages/app/dist/index.html /opt/app-root/src/packages/app/dist/index.html.tmpl
 
 # Fix for https://issues.redhat.com/browse/RHIDP-728
-RUN mkdir -p /opt/app-root/src/.npm; chown -R 1001:1001 /opt/app-root/src/.npm
+#RUN mkdir -p /opt/app-root/src/.npm; chown -R 1001:1001 /opt/app-root/src/.npm
 
 # The fix-permissions script is important when operating in environments that dynamically use a random UID at runtime, such as OpenShift.
 # The upstream backstage image does not account for this and it causes the container to fail at runtime.
 # suppress warnings about dereferencing symlinks
-RUN fix-permissions ./ 2>&1 | grep -v "chgrp: cannot dereference" || true
+#RUN fix-permissions ./ 2>&1 | grep -v "chgrp: cannot dereference" || true
 
 # Switch to nodejs user
 USER 1001
